openapi: 3.0.0
info:
  title: Gateway API
  version: 1.0.0
paths:
  /v1/payments:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePayment'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
  /v1/payments/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
components:
  schemas:
    Money:
      type: object
      properties:
        currency:
          type: string
        value:
          type: string
    CreatePayment:
      type: object
      properties:
        amount:
          $ref: '#/components/schemas/Money'
        method:
          type: string
        customer:
          type: object
          properties:
            email:
              type: string
    Payment:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        amount:
          $ref: '#/components/schemas/Money'
