version: "3.9"
services:
  db:
    image: postgres:15-alpine
    env_file: .env
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports: ["9092:9092", "29092:29092"]
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  gateway-api:
    build: ./services/gateway-api
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  core-payments:
    build: ./services/core-payments
    ports: ["8080:8080", "9090:9090"]
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  adapter-kora:
    build: ./services/adapter-kora
    ports: ["8100:8100"]
    depends_on:
      - kafka

  webhook-dispatcher:
    build: ./services/webhook-dispatcher
    ports: ["8200:8200"]
    depends_on:
      - kafka

  ledger:
    build: ./services/ledger
    ports: ["8300:8300"]
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    depends_on:
      - gateway-api
