version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://app:app@postgres:5432/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  pgdata:
